export const OCCUPATIONS = {
  Healthcare: [
    'Doctor',
    'Nurse',
    'Pharmacist',
    'Surgeon',
    'Dentist',
    'Physiotherapist',
    'Radiologist',
    'Paramedic',
    'Medical Laboratory Technician',
    'Psychologist',
    'Dietitian/Nutritionist',
  ],
  'Technology and IT': [
    'Software Developer',
    'Data Scientist',
    'Web Developer',
    'Cybersecurity Analyst',
    'IT Support Specialist',
    'Network Administrator',
    'Systems Engineer',
    'Cloud Architect',
    'Database Administrator',
    'DevOps Engineer',
    'UI/UX Designer',
  ],
  Education: [
    'Teacher',
    'College Professor',
    'School Principal',
    'Librarian',
    'Education Consultant',
    'Curriculum Developer',
    'Tutor',
    'Researcher',
    'Special Education Teacher',
  ],
  'Finance and Business': [
    'Accountant',
    'Financial Analyst',
    'Investment Banker',
    'Auditor',
    'Tax Consultant',
    'Actuary',
    'Economist',
    'Business Analyst',
    'Marketing Manager',
    'Human Resources Specialist',
    'Sales Representative',
  ],
  Engineering: [
    'Civil Engineer',
    'Mechanical Engineer',
    'Electrical Engineer',
    'Software Engineer',
    'Chemical Engineer',
    'Aerospace Engineer',
    'Industrial Engineer',
    'Environmental Engineer',
    'Biomedical Engineer',
    'Structural Engineer',
  ],
  'Construction and Skilled Trades': [
    'Architect',
    'Carpenter',
    'Electrician',
    'Plumber',
    'Mason',
    'Construction Manager',
    'Surveyor',
    'Welder',
    'HVAC Technician',
    'Crane Operator',
  ],
  'Arts, Media, and Entertainment': [
    'Graphic Designer',
    'Writer/Author',
    'Photographer',
    'Videographer',
    'Actor',
    'Musician',
    'Journalist',
    'Editor',
    'Art Director',
    'Animator',
  ],
  'Public Services': [
    'Police Officer',
    'Firefighter',
    'Military Officer',
    'Social Worker',
    'Postal Worker',
    'Emergency Dispatcher',
    'Politician',
    'Diplomat',
    'Urban Planner',
  ],
  Transportation: [
    'Pilot',
    'Flight Attendant',
    'Truck Driver',
    'Train Conductor',
    'Logistics Coordinator',
    'Ship Captain',
    'Delivery Driver',
    'Automotive Mechanic',
  ],
  'Hospitality and Tourism': [
    'Hotel Manager',
    'Chef',
    'Event Planner',
    'Travel Agent',
    'Tour Guide',
    'Bartender',
    'Housekeeping Staff',
  ],
  'Science and Research': [
    'Scientist',
    'Research Assistant',
    'Lab Technician',
    'Environmental Scientist',
    'Archaeologist',
    'Astronomer',
  ],
  'Retail and Customer Service': [
    'Store Manager',
    'Cashier',
    'Retail Salesperson',
    'Customer Service Representative',
    'Visual Merchandiser',
  ],
  'Agriculture and Food': [
    'Farmer',
    'Agricultural Scientist',
    'Food Technologist',
    'Horticulturist',
    'Fisherman',
    'Florist',
  ],
  Legal: ['Lawyer', 'Judge', 'Paralegal', 'Legal Secretary', 'Court Reporter'],
  Domestic: ['House Wife'],
  Others: [
    'Entrepreneur',
    'Real Estate Agent',
    'Personal Trainer',
    'Barber/Hairdresser',
    'Interior Designer',
    'Tattoo Artist',
    'Fashion Designer',
    'Interpreter/Translator',
    'Consultant',
    'Motivational Speaker',
  ],
};
